### ISSUE TITLE
interp->errorLine is depricated  in tcl 8.6 

### ISSUE THREAD

**Issue by cwjolly** [tDOM/tdom#22]
replace reference to interp->errorLine at line 5937 in generic/tcldom.c with Tcl_GetErrorLine(interp).

**Comment by kolewu** [comment]
What version (commit or whatever) are you referring?  This is solved since 2012 in commit dd18c02ac88a08ad42f1036f93bae40d5018bf39

But it is true, that there is no stable release with this fix.

**Comment by rkeene** [comment]
This bug still seems to be present in the latest release (0.8.3).

**Comment by kolewu** [comment]
Yes, that's what I meant by writing:

> there is no stable release with this fix

And unfortunately this is still true :disappointed:
